trigger: none
pr: none
pool:
  vmImage: ubuntu-latest
jobs:
  - job: checkParameters
    displayName: Check parameters
    steps:
      - checkout: none

      - script: |-
          set -Eeuxo pipefail
          echo "Subscription name: '$(subscriptionName)'"
          if [ -z "$(subscriptionName)" ]
          then
            echo "A value for the 'subscriptionName' variable must be provided" > /dev/stderr
            exit 1
          fi

          echo "Location name: '$(locationName)'"
          if [ -z "$(locationName)" ]
          then
            echo "A value for the 'locationName' variable must be provided" > /dev/stderr
            exit 1
          fi

          echo "Environment name: '$(environmentName)'"
          if [ -z "$(environmentName)" ]
          then
            echo "A value for the 'environmentName' variable must be provided" > /dev/stderr
            exit 1
          fi

          echo "Subscription ID: '$(subscriptionId)'"
          if [ -z "$(subscriptionId)" ]
          then
            echo "A value for the 'subscriptionId' variable must be provided" > /dev/stderr
            exit 1
          fi

          echo "Application code: '$(applicationCode)'"
          if [ -z "$(applicationCode)" ]
          then
            echo "A value for the 'applicationCode' variable must be provided" > /dev/stderr
            exit 1
          fi

          echo "Application short code: '$(applicationShortCode)'"
          if [ -z "$(applicationShortCode)" ]
          then
            echo "A value for the 'applicationShortCode' variable must be provided" > /dev/stderr
            exit 1
          fi

          echo "Environment category: '$(environmentCategory)'"
          if [ -z "$(environmentCategory)" ]
          then
            echo "A value for the 'environmentCategory' variable must be provided" > /dev/stderr
            exit 1
          fi

          echo "Kubernetes version: '$(kubernetesVersion)'"
          if [ -z "$(kubernetesVersion)" ]
          then
            echo "A value for the 'kubernetesVersion' variable must be provided" > /dev/stderr
            exit 1
          fi

          echo "SendGrid email: '$(sendGridEmail)'"
          if [ -z "$(sendGridEmail)" ]
          then
            echo "A value for the 'sendGridEmail' variable must be provided" > /dev/stderr
            exit 1
          fi

          echo "System Admins: '$(sysAdmins)'"
          if [ -z "$(sysAdmins)" ]
          then
            echo "A json format value for the 'sysAdmins' variable must be provided" > /dev/stderr
            exit 1
          fi
        displayName: Check parameters

  - template: ../templates/jobs-deploy-infra.yaml
    parameters:
      subscriptionName: $(subscriptionName)
      locationName: $(locationName)
      environmentName: $(environmentName)
      subscriptionId: $(subscriptionId)
      applicationCode: $(applicationCode)
      applicationShortCode: $(applicationShortCode)
      environmentCategory: $(environmentCategory)
      kubernetesVersion: $(kubernetesVersion)
      sendgridEmail: $(sendGridEmail)
      sysAdmins: $(sysAdmins)