Param(
    [Parameter(Mandatory = $true)]
    [String]
    $AppConfigurationName
)

az appconfig kv delete --name $AppConfigurationName --key "Actions:actionseventhubname" --yes
az appconfig kv delete --name $AppConfigurationName --key "Actions:logicappendpointurl" --yes
az appconfig kv delete --name $AppConfigurationName --key "Actions:solutionwebsiteurl" --yes
az appconfig kv delete --name $AppConfigurationName --key "Actions:storagecontainer" --yes
az appconfig kv delete --name $AppConfigurationName --key "Actions:templatefolder" --yes
az appconfig kv delete --name $AppConfigurationName --key "ConfigService:Actions:armendpointurl" --yes
az appconfig kv delete --name $AppConfigurationName --key "ConfigService:Actions:managementapiversion" --yes
az appconfig kv delete --name $AppConfigurationName --key "ConfigService:Actions:office365connectionurl" --yes
az appconfig kv delete --name $AppConfigurationName --key "ConfigService:Actions:solutionname" --yes
az appconfig kv delete --name $AppConfigurationName --key "ConfigService:Actions:subscriptionid" --yes
az appconfig kv delete --name $AppConfigurationName --key "ConfigService:azureMapsKey" --yes
az appconfig kv delete --name $AppConfigurationName --key "ConfigService:seedtemplate" --yes
az appconfig kv delete --name $AppConfigurationName --key "ConfigService:solutiontype" --yes
az appconfig kv delete --name $AppConfigurationName --key "ConfigService:webserviceport" --yes
az appconfig kv delete --name $AppConfigurationName --key "ExternalDependencies:authWebServiceUrl" --yes
az appconfig kv delete --name $AppConfigurationName --key "ExternalDependencies:configwebserviceurl" --yes
az appconfig kv delete --name $AppConfigurationName --key "ExternalDependencies:devicesimulationwebserviceurl" --yes
az appconfig kv delete --name $AppConfigurationName --key "ExternalDependencies:diagnosticsmaxlogretries" --yes
az appconfig kv delete --name $AppConfigurationName --key "ExternalDependencies:diagnosticswebserviceurl" --yes
az appconfig kv delete --name $AppConfigurationName --key "ExternalDependencies:identitygatewaywebserviceurl" --yes
az appconfig kv delete --name $AppConfigurationName --key "ExternalDependencies:storageadapterwebservicetimeout" --yes
az appconfig kv delete --name $AppConfigurationName --key "ExternalDependencies:storageadapterwebserviceurl" --yes
az appconfig kv delete --name $AppConfigurationName --key "ExternalDependencies:telemetryWebServiceUrl" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:AzureActiveDirectory:aadappid" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:AzureActiveDirectory:aadappsecret" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:AzureActiveDirectory:aadtenantid" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:AzureB2CBaseUri" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:ClientAuth:CORSWhiteList" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:ClientAuth:JWT:aadappid" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:ClientAuth:JWT:allowedalgorithms" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:ClientAuth:JWT:audience" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:ClientAuth:JWT:authissuer" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:ClientAuth:JWT:clockskewseconds" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:ClientAuth:authtype" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:CosmosDb:documentdbconnectionstring" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:CosmosDb:rus" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:KeyVault:name" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:AcquireToken" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:CreateDeployments" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:CreateDeviceGroups" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:CreateDevices" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:CreateJobs" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:CreatePackages" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:CreateRules" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:DeleteAlarms" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:DeleteDeployments" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:DeleteDeviceGroups" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:DeleteDevices" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:DeletePackages" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:DeleteRules" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:DeleteTenant" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:ReadAll" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:UpdateAlarms" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:UpdateDeviceGroups" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:UpdateDevices" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:UpdateRules" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:UpdateSIMManagement" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:admin:UserManage" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:Permissions:readOnly:ReadAll" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:StorageAccount:name" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:developmentMode" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:instrumentationKey" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:location" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:resourceGroup" --yes
az appconfig kv delete --name $AppConfigurationName --key "Global:subscriptionId" --yes
az appconfig kv delete --name $AppConfigurationName --key "IdentityGatewayService:webserviceport" --yes
az appconfig kv delete --name $AppConfigurationName --key "IothubManagerService:DevicePropertiesCache:rebuildtimeout" --yes
az appconfig kv delete --name $AppConfigurationName --key "IothubManagerService:DevicePropertiesCache:ttl" --yes
az appconfig kv delete --name $AppConfigurationName --key "IothubManagerService:DevicePropertiesCache:whitelist" --yes
az appconfig kv delete --name $AppConfigurationName --key "IothubManagerService:webserviceport" --yes
az appconfig kv delete --name $AppConfigurationName --key "KeyVault:aadappid" --yes
az appconfig kv delete --name $AppConfigurationName --key "KeyVault:aadappsecret" --yes
az appconfig kv delete --name $AppConfigurationName --key "KeyVault:name" --yes
az appconfig kv delete --name $AppConfigurationName --key "KeyVault:newName" --yes
az appconfig kv delete --name $AppConfigurationName --key "Logging:includescopes" --yes
az appconfig kv delete --name $AppConfigurationName --key "Logging:loglevel:0" --yes
az appconfig kv delete --name $AppConfigurationName --key "Logging:loglevel:1" --yes
az appconfig kv delete --name $AppConfigurationName --key "Logging:loglevel:2" --yes
az appconfig kv delete --name $AppConfigurationName --key "StorageAccount:name" --yes
az appconfig kv delete --name $AppConfigurationName --key "StorageAdapter:cosmosconnectionstring" --yes
az appconfig kv delete --name $AppConfigurationName --key "StorageAdapter:documentDb" --yes
az appconfig kv delete --name $AppConfigurationName --key "StorageAdapter:documentdbrus" --yes
az appconfig kv delete --name $AppConfigurationName --key "StorageAdapter:messages" --yes
az appconfig kv delete --name $AppConfigurationName --key "StorageAdapter:pcs" --yes
az appconfig kv delete --name $AppConfigurationName --key "StorageAdapter:storagetype" --yes
az appconfig kv delete --name $AppConfigurationName --key "StorageAdapter:webserviceport" --yes
az appconfig kv delete --name $AppConfigurationName --key "TelemetryService:Alarms:collection" --yes
az appconfig kv delete --name $AppConfigurationName --key "TelemetryService:Alarms:database" --yes
az appconfig kv delete --name $AppConfigurationName --key "TelemetryService:Alarms:maxdeleteretries" --yes
az appconfig kv delete --name $AppConfigurationName --key "TelemetryService:Alarms:storage_type" --yes
az appconfig kv delete --name $AppConfigurationName --key "TelemetryService:Messages:collection" --yes
az appconfig kv delete --name $AppConfigurationName --key "TelemetryService:Messages:database" --yes
az appconfig kv delete --name $AppConfigurationName --key "TelemetryService:Messages:telemetrystoragetype" --yes
az appconfig kv delete --name $AppConfigurationName --key "TelemetryService:TimeSeries:apiversion" --yes
az appconfig kv delete --name $AppConfigurationName --key "TelemetryService:TimeSeries:audience" --yes
az appconfig kv delete --name $AppConfigurationName --key "TelemetryService:TimeSeries:authority" --yes
az appconfig kv delete --name $AppConfigurationName --key "TelemetryService:TimeSeries:explorerurl" --yes
az appconfig kv delete --name $AppConfigurationName --key "TelemetryService:TimeSeries:timeout" --yes
az appconfig kv delete --name $AppConfigurationName --key "TelemetryService:TimeSeries:tsidataaccessfqdn" --yes
az appconfig kv delete --name $AppConfigurationName --key "TelemetryService:rulestemplatesfolder" --yes
az appconfig kv delete --name $AppConfigurationName --key "TelemetryService:webserviceport" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:automationAccountName" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:cosmosAccount" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:cosmosConnectionSetting" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:cosmosDbConnection" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:cosmosDbEndpoint" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:cosmosDbToken" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:cosmoskey" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:createIotHubWebHookName" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:databaseName" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:deleteIotHubWebHookName" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:documentDBConnectionString" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:lifecycleEventHubConnString" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:lifecycleFunctionName" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:lifecycleFunctionUri" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:setAppConfigEndpoint" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:setAppConfigFunction" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:tableName" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:telemetryEventHubConnString" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:telemetryFunctionName" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:telemetryFunctionUri" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:twinChangeEventHubConnString" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:twinChangeFunctionName" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:twinChangeFunctionUri" --yes
az appconfig kv delete --name $AppConfigurationName --key "TenantManagerService:webserviceport" --yes